-- UPDATE K_ANALYSIS_DETAIL 

ALTER TABLE CADDIS2.K_ANALYSIS_DETAILS
    ADD (LL_MEASURE_TYPE_ID NUMBER(11));

ALTER TABLE CADDIS2.K_ANALYSIS_DETAILS
    ADD (RESPONSE_MEASURE VARCHAR2(20));

ALTER TABLE K_ANALYSIS_DETAILS
ADD CONSTRAINT FK_P_LIST_MEASURE_TYPE_ID FOREIGN KEY (LL_MEASURE_TYPE_ID) REFERENCES CADDIS2.P_LIST_ITEM (LL_ID) ON DELETE SET NULL;

