--UPDATE K_CAUSE_EFFECT

ALTER TABLE K_CAUSE_EFFECT
    ADD (CAUSE_MEASURED VARCHAR2(250));

ALTER TABLE K_CAUSE_EFFECT
    ADD (EFFECT_MEASURED VARCHAR2(250));
    
UPDATE K_CAUSE_EFFECT
     SET CAUSE_MEASURED = GET_ITEM_CODE(LL_CAUSE_MEASURED_ID),
            EFFECT_MEASURED = GET_ITEM_CODE(LL_EFFECT_MEASURED_ID);
            

 ALTER TABLE K_CAUSE_EFFECT
DROP CONSTRAINT FK_K_CAUSE_EFFECT_EFFE_MEAS_ID;

ALTER TABLE K_CAUSE_EFFECT
DROP CONSTRAINT FK_K_CAUSE_EFFECT_MEASURED_ID;     

ALTER TABLE K_CAUSE_EFFECT
  DROP COLUMN LL_CAUSE_MEASURED_ID CASCADE CONSTRAINTS;

ALTER TABLE K_CAUSE_EFFECT
  DROP COLUMN LL_EFFECT_MEASURED_ID CASCADE CONSTRAINTS;