ALTER TABLE P_STANDARD_TERM
 DROP PRIMARY KEY CASCADE;

DROP TABLE P_STANDARD_TERM CASCADE CONSTRAINTS;

CREATE TABLE P_STANDARD_TERM
(
  STANDARD_TERM_ID    NUMBER(12)                NOT NULL,
  STANDARD_TERM       VARCHAR2(200 BYTE)        NOT NULL,
  IS_EEL_TERM         CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  STANDARD_TERM_DESC  VARCHAR2(1000 BYTE),
  CREATE_DATE         DATE,
  CREATE_USER         VARCHAR2(50 BYTE),
  UPDATE_DATE         DATE,
  UPDATE_USER         VARCHAR2(50 BYTE),
  CITATION_USED       VARCHAR2(1000 BYTE),
  LL_LEGEND_TYPE_ID   NUMBER(11),
  IS_APPROVED         CHAR(1 BYTE),
  SEARCH_KEYWORDS     VARCHAR2(4000 BYTE)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX FK_P_STD_TM_LL_LEG_TYP_ID ON P_STANDARD_TERM
(LL_LEGEND_TYPE_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_P_STANDARD_TERM ON P_STANDARD_TERM
(STANDARD_TERM_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX UX_P_STD_TERM_STD_TERM ON P_STANDARD_TERM
(STANDARD_TERM)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER "P_STANDARD_TERM_T1" 
 BEFORE INSERT OR UPDATE ON  "P_STANDARD_TERM" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE P_STANDARD_TERM ADD (
  CONSTRAINT C01_P_STANDARD_TERM_1862753408
  CHECK (IS_EEL_TERM IN ('Y', 'N')),
  CONSTRAINT PK_P_STANDARD_TERM
  PRIMARY KEY
  (STANDARD_TERM_ID)
  USING INDEX PK_P_STANDARD_TERM,
  CONSTRAINT UX_P_STD_TERM_STD_TERM
  UNIQUE (STANDARD_TERM)
  USING INDEX UX_P_STD_TERM_STD_TERM);

ALTER TABLE P_STANDARD_TERM ADD (
  CONSTRAINT FK_P_STD_TM_LL_LEG_TYP_ID 
  FOREIGN KEY (LL_LEGEND_TYPE_ID) 
  REFERENCES P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);

--Seq
DROP SEQUENCE SEQ_STANDARD_TERM_ID;

CREATE SEQUENCE SEQ_STANDARD_TERM_ID
  START WITH 1498
  MAXVALUE 99999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
(
  CAUSE_EFFECT_LINKAGE_ID  NUMBER(12)           NOT NULL,
  CAUSE_ID                 NUMBER(12)           NOT NULL,
  EFFECT_ID                NUMBER(12)           NOT NULL,
  CITATION_ID              NUMBER(11)           NOT NULL,
  CREATE_DATE              DATE,
  CREATE_USER              VARCHAR2(50 BYTE),
  UPDATE_DATE              DATE,
  UPDATE_USER              VARCHAR2(50 BYTE),
  LL_CAUSE_TRAJECTORY_ID   NUMBER(11),
  LL_EFFECT_TRAJECTORY_ID  NUMBER(11)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_CS_EFF_LK_LL_CS_TRA_ID ON CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
(LL_CAUSE_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CS_EFF_LK_LL_EFF_TRA_ID ON CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
(LL_EFFECT_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_CAUSE_EFFECT_LINKAGE ON CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
(CAUSE_EFFECT_LINKAGE_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.UX_P_CAUSE_EFFECT_LK_5ID ON CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE
(CAUSE_ID, EFFECT_ID, CITATION_ID, LL_CAUSE_TRAJECTORY_ID, LL_EFFECT_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE ADD (
  CONSTRAINT PK_P_CAUSE_EFFECT_LINKAGE
  PRIMARY KEY
  (CAUSE_EFFECT_LINKAGE_ID)
  USING INDEX CADDIS_DEV.PK_P_CAUSE_EFFECT_LINKAGE,
  CONSTRAINT UX_P_CAUSE_EFFECT_LK_5ID
  UNIQUE (CAUSE_ID, EFFECT_ID, CITATION_ID, LL_CAUSE_TRAJECTORY_ID, LL_EFFECT_TRAJECTORY_ID)
  USING INDEX CADDIS_DEV.UX_P_CAUSE_EFFECT_LK_5ID);

ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT_LINKAGE ADD (
  CONSTRAINT FK_P_CAUSE_EFFECT_LK_CAUSE_ID 
  FOREIGN KEY (CAUSE_ID) 
  REFERENCES CADDIS_DEV.P_STANDARD_TERM (STANDARD_TERM_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_LK_CT_ID 
  FOREIGN KEY (CITATION_ID) 
  REFERENCES CADDIS_DEV.P_CITATION (CITATION_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_LK_EFFECT_ID 
  FOREIGN KEY (EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_STANDARD_TERM (STANDARD_TERM_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CS_EFF_LK_LL_CS_TRA_ID 
  FOREIGN KEY (LL_CAUSE_TRAJECTORY_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CS_EFF_LK_LL_EFF_TRA_ID 
  FOREIGN KEY (LL_EFFECT_TRAJECTORY_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);

CREATE SEQUENCE CADDIS_DEV.SEQ_CAUSE_EFFECT_LINKAGE_ID
  START WITH 7546
  MAXVALUE 999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;