DROP TABLE CADDIS_DEV.T_LIST CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.T_LIST
(
  LIST_ID      NUMBER(10),
  SESSION_ID   VARCHAR2(4000 BYTE),
  UPDATE_DATE  DATE,
  UPDATE_BY    VARCHAR2(100 BYTE)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

