--ALTER TABLE CADDIS_DEV.P_CAUSE_MEASURED
 --DROP PRIMARY KEY CASCADE;

---DROP TABLE CADDIS_DEV.P_CAUSE_MEASURED CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_CAUSE_MEASURED
(
  CAUSE_MEASURED_ID          NUMBER(11)         NOT NULL,
  MEASUREMENT_METHOD         VARCHAR2(300 BYTE),
  DATA_ORIGIN_INFO           VARCHAR2(250 BYTE),
  CAUSE_COMMENT              VARCHAR2(4000 BYTE),
  CREATE_DATE                DATE,
  CREATE_USER                VARCHAR2(50 BYTE),
  UPDATE_DATE                DATE,
  UPDATE_USER                VARCHAR2(50 BYTE),
  LL_CAUSE_MEASURED_UNIT_ID  NUMBER(11),
  LL_MEASUREMENT_TYPE_ID     NUMBER(11),
  LL_MEDIA_ID                NUMBER(11),
  CAUSE_EFFECT_ID            NUMBER(12)         NOT NULL,
  CAUSE_SET_ATTRIBUTE        VARCHAR2(1000 CHAR),
  CAUSE_SET_COMMENTS         VARCHAR2(4000 CHAR)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_CAUSE_MEASURED_CA_EFF_ID ON CADDIS_DEV.P_CAUSE_MEASURED
(CAUSE_EFFECT_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CAUSE_MS_LL_CS_MS_UNIT_ID ON CADDIS_DEV.P_CAUSE_MEASURED
(LL_CAUSE_MEASURED_UNIT_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CAUSE_MS_LL_MEDIA_ID ON CADDIS_DEV.P_CAUSE_MEASURED
(LL_MEDIA_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CAUSE_MS_LL_MS_TYPE_ID ON CADDIS_DEV.P_CAUSE_MEASURED
(LL_MEASUREMENT_TYPE_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_CAUSE_MS_CAUSE_MS_ID ON CADDIS_DEV.P_CAUSE_MEASURED
(CAUSE_MEASURED_ID)
LOGGING
TABLESPACE CADDIS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_CAUSE_MEASURED_T1" 
 BEFORE INSERT OR UPDATE ON  "P_CAUSE_MEASURED" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_CAUSE_MEASURED ADD (
  CONSTRAINT PK_P_CAUSE_MS_CAUSE_MS_ID
  PRIMARY KEY
  (CAUSE_MEASURED_ID)
  USING INDEX CADDIS_DEV.PK_P_CAUSE_MS_CAUSE_MS_ID);

ALTER TABLE CADDIS_DEV.P_CAUSE_MEASURED ADD (
  CONSTRAINT FK_P_CAUSE_MEASURED_CA_EFF_ID 
  FOREIGN KEY (CAUSE_EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_CAUSE_EFFECT (CAUSE_EFFECT_ID),
  CONSTRAINT FK_P_CAUSE_MS_LL_CS_MS_UNIT_ID 
  FOREIGN KEY (LL_CAUSE_MEASURED_UNIT_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_MS_LL_MEDIA_ID 
  FOREIGN KEY (LL_MEDIA_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_MS_LL_MS_TYPE_ID 
  FOREIGN KEY (LL_MEASUREMENT_TYPE_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);


CREATE SEQUENCE CADDIS_DEV.SEQ_CAUSE_MEASURED_ID
  START WITH 1
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;