GRANT SELECT, UPDATE, DELETE, INSERT ON P_CITATION_FILE  TO CADDIS2_APEX;
GRANT SELECT, UPDATE, DELETE, INSERT ON P_STERM_CATEGORY TO CADDIS2_APEX;

CREATE SYNONYM CADDIS2_APEX.P_CITATION_FILE FOR P_CITATION_FILE;
CREATE SYNONYM CADDIS2_APEX.P_STERM_CATEGORY FOR P_STERM_CATEGORY;

GRANT SELECT ON  SEQ_FILE_ID to CADDIS2_APEX;
GRANT SELECT ON  SEQ_CATEGORY_ID to CADDIS2_APEX;

CREATE SYNONYM CADDIS2_APEX.SEQ_CATEGORY_ID FOR SEQ_CATEGORY_ID;
CREATE SYNONYM CADDIS2_APEX.SEQ_FILE_ID FOR SEQ_FILE_ID;