SELECT a.SHAPE_LINKAGE_ID
	,h.DIAGRAM_ID
	,h.DIAGRAM_NAME
	,a.SHAPE_FROM_ID
	,c.SHAPE_LABEL AS FR_SHAPE_LABEL
	,j.LIST_ITEM_CODE AS FR_SHAPE_TRAJECTORY
	,e.STANDARD_TERM AS FR_STANDARD_TERM
	,e.IS_EEL_TERM AS FR_IS_EEL_TERM
	,e.STANDARD_TERM_DESC AS FR_STANDARD_TERM_DESC
	,a.SHAPE_TO_ID
	,d.SHAPE_LABEL AS TO_SHAPE_LABEL
	,k.LIST_ITEM_CODE AS TO_SHAPE_TRAJECTORY
	,f.STANDARD_TERM AS TO_STANDARD_TERM
	,f.IS_EEL_TERM AS TO_IS_EEL_TERM
	,f.STANDARD_TERM_DESC AS TO_STANDARD_TERM_DESC
	,b.CITATION_ID
	,g.AUTHOR
	,g.TITLE
FROM ICD_SHAPE_LINKAGE a
	,ICD_LINKAGE_CITATION_JOIN b
	,ICD_SHAPE c
	,ICD_SHAPE d
	,P_STANDARD_TERM e
	,P_STANDARD_TERM f
	,P_CITATION g
	,ICD_DIAGRAM h
	,ICD_DIAGRAM_SHAPE_JOIN i
	,V_ICD_LK_SHAPE_LABEL_SYMBOL j
	,V_ICD_LK_SHAPE_LABEL_SYMBOL k
WHERE a.SHAPE_LINKAGE_ID = b.SHAPE_LINKAGE_ID
	AND a.SHAPE_FROM_ID = c.SHAPE_ID
	AND a.SHAPE_TO_ID = d.SHAPE_ID
	AND c.STANDARD_TERM_ID = e.STANDARD_TERM_ID(+)
	AND d.STANDARD_TERM_ID = f.STANDARD_TERM_ID(+)
	AND b.CITATION_ID = g.CITATION_ID
	AND a.SHAPE_FROM_ID = i.SHAPE_ID
	AND i.DIAGRAM_ID = h.DIAGRAM_ID
	AND c.LL_SHAPE_LABEL_SYMBOL_ID = j.LL_ID(+)
	AND d.LL_SHAPE_LABEL_SYMBOL_ID = k.LL_ID(+)
ORDER BY a.SHAPE_LINKAGE_ID
	,b.CITATION_ID;
