
--select max(SEQ_TYPE_ENTITY_ID) from P_LIST_ITEM;

-- check the next value of the sequence and identify the gap

--ALTER SEQUENCE SEQ_TYPE_ENTITY_ID INCREMENT BY 83;

--SELECT SEQ_TYPE_ENTITY_ID.NEXTVAL
--FROM DUAL;

--ALTER SEQUENCE SEQ_TYPE_ENTITY_ID INCREMENT BY 1;

INSERT INTO P_TYPE_ENTITY_NAME(TYPE_ENTITY_ID, TYPE_ENTITY_NAME, CREATE_DATE, CREATE_USER ) VALUES (SEQ_TYPE_ENTITY_ID.NEXTVAL, 'TERM_CATEGORY_TYPE', SYSDATE, 'CADDIS2') ;
INSERT INTO P_TYPE_ENTITY_NAME(TYPE_ENTITY_ID, TYPE_ENTITY_NAME, CREATE_DATE, CREATE_USER ) VALUES (SEQ_TYPE_ENTITY_ID.NEXTVAL, 'RESPONSE_MEASURE_TYPE',SYSDATE, 'CADDIS2');

-- insert standard term category types
INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'MARS'
    ,'MARS'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'TERM_CATEGORY_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'WQA'
    ,'WQA'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'TERM_CATEGORY_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Source'
    ,'Source'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'TERM_CATEGORY_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Stressor'
    ,'Stressor'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'TERM_CATEGORY_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Response'
    ,'Response'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'TERM_CATEGORY_TYPE';

--insert measrue reponse type
INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Mean difference'
    ,'Mean difference'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Standardized mean difference'
    ,'Standardized mean difference'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Correlation coefficient'
    ,'Correlation coefficient'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'R-squared'
    ,'R-squared'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Slope coefficient (beta)'
    ,'Slope coefficient (beta)'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Response ratio'
    ,'Response ratio'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Odds ratio'
    ,'Odds ratio'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Relative risk/risk ratio'
    ,'Relative risk/risk ratio'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Attributable risk'
    ,'Attributable risk'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Risk difference'
    ,'Risk difference'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Hazard ratio'
    ,'Hazard ratio'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';

INSERT INTO P_LIST_ITEM (
    LL_ID
    ,TYPE_ENTITY_ID
    ,LIST_ITEM_CODE
    ,LIST_ITEM_DESCRIPTION
    ,CREATE_DATE
    ,CREATE_USER
    )
SELECT SEQ_LL_ID.NEXTVAL
    ,TYPE_ENTITY_ID
    ,'Other'
    ,'Other'
    ,SYSDATE
    ,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'RESPONSE_MEASURE_TYPE';