/* The following scripts update the look values stored in P_LIST_ITEM table */
-- 1. Synch the SEQUENCE for LL_ID if needed
/* Change the incremental value based on the difference between 
the next value of the sequence and max value of the LL_ID.
Make sure to set the incremental value back to 1. */

-- to find the max LL_ID
select max(LL_ID) from P_LIST_ITEM;

-- check the next value of the sequence and identify the gap

ALTER SEQUENCE SEQ_LL_ID INCREMENT BY 10139;

SELECT SEQ_LL_ID.NEXTVAL
FROM DUAL;

ALTER SEQUENCE SEQ_LL_ID INCREMENT BY 1;

-- verify the last number of the sequence
SELECT LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_LL_ID';

-- 2. Add new Source Data
INSERT INTO P_LIST_ITEM (
	LL_ID
	,TYPE_ENTITY_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,CREATE_DATE
	,CREATE_USER
	)
SELECT SEQ_LL_ID.NEXTVAL
	,TYPE_ENTITY_ID
	,'not available'
	,'not available'
	,SYSDATE
	,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'SOURCE_DATA';

-- 3. Add new Study Type
INSERT INTO P_LIST_ITEM (
	LL_ID
	,TYPE_ENTITY_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,CREATE_DATE
	,CREATE_USER
	)
SELECT SEQ_LL_ID.NEXTVAL
	,TYPE_ENTITY_ID
	,'Model'
	,'Model'
	,SYSDATE
	,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'STUDY TYPE';

INSERT INTO P_LIST_ITEM (
	LL_ID
	,TYPE_ENTITY_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,CREATE_DATE
	,CREATE_USER
	)
SELECT SEQ_LL_ID.NEXTVAL
	,TYPE_ENTITY_ID
	,'Other'
	,'Other'
	,SYSDATE
	,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'STUDY TYPE';

INSERT INTO P_LIST_ITEM (
	LL_ID
	,TYPE_ENTITY_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,CREATE_DATE
	,CREATE_USER
	)
SELECT SEQ_LL_ID.NEXTVAL
	,TYPE_ENTITY_ID
	,'Not Available'
	,'Not Available'
	,SYSDATE
	,'SYSTEM'
FROM P_TYPE_ENTITY_NAME
WHERE TYPE_ENTITY_NAME = 'STUDY TYPE';

-- 4. This script update the view to filter out the archived values
CREATE OR REPLACE FORCE VIEW V_ECOREGION (
	LL_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,IS_PENDING
	,IS_ARCHIVED
	,ORDER_NUMBER
	,REVIEWER
	,ENTERED_BY
	,DATETIME
	,LIST_ITEM_DESCRIPTION_LONG
	,LL_PARA_CLASS_ID
	,LL_PARA_GROUP_ID
	,LL_ID_PARENT
	) AS

SELECT LL_ID
	,LIST_ITEM_CODE
	,LIST_ITEM_DESCRIPTION
	,IS_PENDING
	,IS_ARCHIVED
	,ORDER_NUMBER
	,REVIEWER
	,ENTERED_BY
	,DATETIME
	,LIST_ITEM_DESCRIPTION_LONG
	,LL_PARA_CLASS_ID
	,LL_PARA_GROUP_ID
	,LL_ID_PARENT
FROM P_LIST_ITEM
WHERE TYPE_ENTITY_ID = (
		SELECT TYPE_ENTITY_ID
		FROM P_TYPE_ENTITY_NAME
		WHERE TYPE_ENTITY_NAME = 'ECOREGION'
		)
	AND IS_ARCHIVED = 0;
