--SELECT * FROM P_TYPE_ENTITY_NAME N WHERE N.TYPE_ENTITY_NAME = 'STUDY TYPE'
delete 
from k_cause_effect

delete
from k_dataset

SELECT TYPE_ENTITY_ID FROM P_TYPE_ENTITY_NAME N WHERE N.TYPE_ENTITY_NAME = 'HABITAT'