begin

   SAVEPOINT start_tran;
   INSERT INTO P_LIST_ITEM(LL_ID, LL_ID_PARENT, TYPE_ENTITY_ID, LIST_ITEM_CODE, LIST_ITEM_DESCRIPTION, CREATE_DATE, CREATE_USER  )
    SELECT LL_ID, LL_ID_PARENT, TYPE_ENTITY_ID, LIST_ITEM_CODE, LIST_ITEM_DESCRIPTION, CREATE_DATE, CREATE_USER
     FROM CADDIS.P_LIST_ITEM WHERE  LL_ID NOT IN (SELECT LL_ID FROM CADDIS2.P_LIST_ITEM);

/* citation */
    INSERT INTO P_CITATION ( CITATION_ID, LL_PUBLICATION_ID, LL_PUBLICATION_TYPE_ID,
        AUTHOR, YEAR, TITLE, KEYWORD, ABSTRACT, ANNOTATION, CITATION_URL, IS_APPROVED, DOI, VOLUME, ISSUE,
        START_PAGE, END_PAGE, BOOK, EDITORS, PUBLISHERS, REPORT_NUMBER, PAGES, SOURCE,
         TYPE, IS_EXIT_DISCLAIMER, CREATE_DATE, CREATE_USER)
    SELECT CITATION_ID, LL_PUBLICATION_ID, LL_PUBLICATION_TYPE_ID,
        AUTHOR, YEAR, TITLE, KEYWORD, ABSTRACT, ANNOTATION, CITATION_URL, IS_APPROVED, DOI, VOLUME, ISSUE,
        START_PAGE, END_PAGE, BOOK, EDITORS, PUBLISHERS, REPORT_NUMBER, PAGES, SOURCE,
         TYPE, IS_EXIT_DISCLAIMER, CREATE_DATE, CREATE_USER
     FROM CADDIS.P_CITATION 
    WHERE CITATION_ID IN (SELECT DISTINCT CITATION_ID  FROM CADDIS.ICD_LINKAGE_CITATION_JOIN WHERE CITATION_ID IN (
                                                select CITATION_ID from TMP_CITATION_UPDATE 
                                                where  tobedelete is not null  ) )
     OR ( CITATION_ID > 2455 AND CITATION_ID NOT IN (2729, 2725, 2665, 2749 ));
 
 INSERT INTO P_CADDIS_PAGE_CITATION_JOIN ( CADDIS_PAGE_CITATION_ID, LL_CADDIS_PAGE_ID, CITATION_ID, CREATE_USER)
    SELECT CADDIS_PAGE_CITATION_ID, LL_CADDIS_PAGE_ID, CITATION_ID, CREATE_USER 
     FROM  CADDIS.P_CADDIS_PAGE_CITATION_JOIN
     WHERE CADDIS_PAGE_CITATION_ID NOT IN (SELECT CADDIS_PAGE_CITATION_ID FROM P_CADDIS_PAGE_CITATION_JOIN);
     
 EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO start_tran;
    RAISE;
    
end;