DROP TABLE CADDIS_DEV.MV_NEW_CITATION_DOWNLOAD CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.MV_NEW_CITATION_DOWNLOAD
(
  CITATION_ID         NUMBER(11)                NOT NULL,
  PUBLICATION         VARCHAR2(50 CHAR),
  AUTHOR              VARCHAR2(500 BYTE),
  TITLE               VARCHAR2(500 BYTE),
  ABSTRACT            VARCHAR2(4000 BYTE),
  VOLUME              NUMBER(4),
  ISSUE               VARCHAR2(50 BYTE),
  CITATION_URL        VARCHAR2(255 BYTE),
  YEAR                VARCHAR2(5 BYTE),
  START_PAGE          VARCHAR2(50 BYTE),
  END_PAGE            VARCHAR2(50 BYTE),
  SOURCE_DATA         VARCHAR2(50 CHAR),
  STUDY_TYPE          VARCHAR2(50 CHAR),
  STUDY_DESIGN        VARCHAR2(50 CHAR),
  SAMPLE_SELECTION    VARCHAR2(50 CHAR),
  CONTROL_SAMPLES     NUMBER(11),
  CONTROL_REPLICATES  NUMBER(11),
  IMPACT_SAMPLES      NUMBER(11),
  IMPACT_REPLICATES   NUMBER(11),
  MIN_LATITUDE        NUMBER(10,8),
  MAX_LATITUDE        NUMBER(10,8),
  MIN_LONG            NUMBER(10,8),
  MAX_LONG            NUMBER(10,8),
  MAX_ELEVATION       NUMBER(11,7),
  MIN_ELEVATION       NUMBER(11,7),
  ELEVATION_UNIT      VARCHAR2(50 CHAR),
  GEOMETRY            VARCHAR2(50 BYTE),
  HABITAT             VARCHAR2(50 CHAR),
  CLIMATE             VARCHAR2(50 CHAR),
  SPATIAL_EXTENT      VARCHAR2(50 CHAR),
  TEMPORAL_EXTENT     VARCHAR2(50 CHAR),
  LOC_STATE           VARCHAR2(4000 BYTE),
  LOC_ECOREGION       VARCHAR2(4000 BYTE),
  LOC_HUC             VARCHAR2(4000 BYTE),
  LOC_COUNTRY         VARCHAR2(4000 BYTE),
  CAUSE_TERM          VARCHAR2(200 BYTE),
  EFFECT_TERM         VARCHAR2(200 BYTE),
  CAUSE_MS_METHOD     VARCHAR2(300 BYTE),
  EFFECT_MS_METHOD    VARCHAR2(3000 BYTE),
  CAUSE_TRAJECTORY    VARCHAR2(50 CHAR),
  CAUSE_MEASURE       VARCHAR2(50 CHAR),
  EFFECT_TRAJECTORY   VARCHAR2(50 CHAR),
  EFFECT_MEASURE      VARCHAR2(50 CHAR),
  P_LEVEL             VARCHAR2(50 BYTE),
  RESPONSE_STRENGTH   VARCHAR2(50 CHAR),
  RESPONSE_FORM       VARCHAR2(50 CHAR),
  EVIDENCE_OF_CAUSE   VARCHAR2(1 CHAR),
  RESPONSE_EQUATION   VARCHAR2(250 BYTE)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

