ALTER TABLE CADDIS_DEV.P_ANALYSIS_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_ANALYSIS_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_ANALYSIS_DETAILS
(
  ANALYSIS_DETAILS_ID           NUMBER(11)      NOT NULL,
  P_LEVEL                       VARCHAR2(50 BYTE),
  STATUS_COMMENT                VARCHAR2(4000 BYTE),
  SOURCE_OF_RESULT              VARCHAR2(50 BYTE),
  RELATIONSHIP_DESC             VARCHAR2(4000 BYTE),
  CREATE_DATE                   DATE,
  CREATE_USER                   VARCHAR2(50 BYTE),
  UPDATE_DATE                   DATE,
  UPDATE_USER                   VARCHAR2(50 BYTE),
  CAUSE_EFFECT_ID               NUMBER(12)      NOT NULL,
  LL_TYPE_OF_RELATION           NUMBER(11),
  LL_STRESSOR_RESPONSE_TYPE_ID  NUMBER(11),
  LL_RESPONSE_STRENGTH_ID       NUMBER(11),
  LL_RESPONSE_FORM_ID           NUMBER(11),
  LL_P_VALUE_ID                 NUMBER(11),
  EVIDENCE_OF_CAUSE             VARCHAR2(1 CHAR) DEFAULT 'N',
  RESPONSE_EQUATION             VARCHAR2(250 BYTE)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_AN_DE_STR_REP_TYPE ON CADDIS_DEV.P_ANALYSIS_DETAILS
(LL_STRESSOR_RESPONSE_TYPE_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_AN_DE_TY_RELATION ON CADDIS_DEV.P_ANALYSIS_DETAILS
(LL_TYPE_OF_RELATION)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_ANALYSIS_DETAILS ON CADDIS_DEV.P_ANALYSIS_DETAILS
(ANALYSIS_DETAILS_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_ANALYSIS_DETAILS_T1" 
 BEFORE INSERT OR UPDATE ON  "P_ANALYSIS_DETAILS" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_ANALYSIS_DETAILS ADD (
  CONSTRAINT C01_EVIDENCE_OF_CAUSE_YN
  CHECK (EVIDENCE_OF_CAUSE IN ('Y', 'N')),
  CONSTRAINT PK_P_ANALYSIS_DETAILS
  PRIMARY KEY
  (ANALYSIS_DETAILS_ID)
  USING INDEX CADDIS_DEV.PK_P_ANALYSIS_DETAILS);

ALTER TABLE CADDIS_DEV.P_ANALYSIS_DETAILS ADD (
  CONSTRAINT FK_ANALS_DET_RESPONSE_FORM_ID 
  FOREIGN KEY (LL_RESPONSE_FORM_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_ANALYI_DETAILS_R_P_VALUE_ID 
  FOREIGN KEY (LL_P_VALUE_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_ANALYSIS_DET_R_RESPONSE_ID 
  FOREIGN KEY (LL_RESPONSE_STRENGTH_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_AN_DE_STR_REP_TYPE 
  FOREIGN KEY (LL_STRESSOR_RESPONSE_TYPE_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_AN_DE_TY_RELATION 
  FOREIGN KEY (LL_TYPE_OF_RELATION) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_ANALYSIS_DETAILS_CS_EF_ID 
  FOREIGN KEY (CAUSE_EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_CAUSE_EFFECT (CAUSE_EFFECT_ID)
  ON DELETE SET NULL);
  
  DROP SEQUENCE CADDIS_DEV.SEQ_ANALYSIS_DETAILS;

CREATE SEQUENCE CADDIS_DEV.SEQ_ANALYSIS_DETAILS
  START WITH 24238
  MAXVALUE 999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
