ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_CAUSE_EFFECT CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_CAUSE_EFFECT
(
  CAUSE_EFFECT_ID          NUMBER(12)           NOT NULL,
  EFFECT_ID                NUMBER(12)           NOT NULL,
  CAUSE_ID                 NUMBER(12)           NOT NULL,
  LL_CAUSE_TRAJECTORY_ID   NUMBER(11),
  LL_CAUSE_MEASURED_ID     NUMBER(11),
  LL_EFFECT_TRAJECTORY_ID  NUMBER(11),
  LL_EFFECT_MEASURED_ID    NUMBER(11),
  LL_ORGANISM_ID           NUMBER(11),
  CREATE_DATE              DATE                 NOT NULL,
  CREATE_USER              VARCHAR2(50 CHAR)    NOT NULL,
  UPDATE_DATE              DATE,
  UPDATE_USER              VARCHAR2(50 CHAR),
  DATASET_ID               NUMBER(11)           NOT NULL,
  CAUSE_COMMENT            VARCHAR2(4000 BYTE),
  EFFECT_COMMENT           VARCHAR2(4000 BYTE),
  LINKAGE_COMMENT          VARCHAR2(4000 BYTE)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_CAUSE_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(CAUSE_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_CAUSE_MEASURE_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(LL_CAUSE_MEASURED_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_CAUSE_TRAJECTOR_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(LL_CAUSE_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_DATASET_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(DATASET_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_EFFECT_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(EFFECT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_EFFECT_MEASURED_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(LL_EFFECT_MEASURED_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_EFFECT_TRAJECTO_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(LL_EFFECT_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CA_EFF_LL_ORGANISM_ID ON CADDIS_DEV.P_CAUSE_EFFECT
(LL_ORGANISM_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_CAUSE_EFFECT ON CADDIS_DEV.P_CAUSE_EFFECT
(CAUSE_EFFECT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.UX_P_CAUSE_EFFECT ON CADDIS_DEV.P_CAUSE_EFFECT
(DATASET_ID, CAUSE_ID, EFFECT_ID, LL_CAUSE_MEASURED_ID, LL_EFFECT_MEASURED_ID, 
LL_ORGANISM_ID, LL_CAUSE_TRAJECTORY_ID, LL_EFFECT_TRAJECTORY_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_CAUSE_EFFECT_T1" 
 BEFORE INSERT OR UPDATE ON  "P_CAUSE_EFFECT" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);         
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT ADD (
  CONSTRAINT PK_P_CAUSE_EFFECT
  PRIMARY KEY
  (CAUSE_EFFECT_ID)
  USING INDEX CADDIS_DEV.PK_P_CAUSE_EFFECT,
  CONSTRAINT UX_P_CAUSE_EFFECT
  UNIQUE (DATASET_ID, CAUSE_ID, EFFECT_ID, LL_CAUSE_MEASURED_ID, LL_EFFECT_MEASURED_ID, LL_ORGANISM_ID, LL_CAUSE_TRAJECTORY_ID, LL_EFFECT_TRAJECTORY_ID)
  USING INDEX CADDIS_DEV.UX_P_CAUSE_EFFECT);

ALTER TABLE CADDIS_DEV.P_CAUSE_EFFECT ADD (
  CONSTRAINT FK_P_CAUSE_EFFECT_CAUSE_ID 
  FOREIGN KEY (CAUSE_ID) 
  REFERENCES CADDIS_DEV.P_STANDARD_TERM (STANDARD_TERM_ID),
  CONSTRAINT FK_P_CAUSE_EFFECT_C_TRAJECT_ID 
  FOREIGN KEY (LL_CAUSE_TRAJECTORY_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_DATASET_ID 
  FOREIGN KEY (DATASET_ID) 
  REFERENCES CADDIS_DEV.P_DATASET (DATASET_ID),
  CONSTRAINT FK_P_CAUSE_EFFECT_EFFECT_ID 
  FOREIGN KEY (EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_STANDARD_TERM (STANDARD_TERM_ID),
  CONSTRAINT FK_P_CAUSE_EFFECT_EFFE_MEAS_ID 
  FOREIGN KEY (LL_EFFECT_MEASURED_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_EFFE_TRAJ_ID 
  FOREIGN KEY (LL_EFFECT_TRAJECTORY_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_MEASURED_ID 
  FOREIGN KEY (LL_CAUSE_MEASURED_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_CAUSE_EFFECT_ORGANISM_ID 
  FOREIGN KEY (LL_ORGANISM_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);
  
 -- DROP SEQUENCE CADDIS_DEV.SEQ_CAUSE_EFFECT_ID;

CREATE SEQUENCE CADDIS_DEV.SEQ_CAUSE_EFFECT_ID
  START WITH 94862
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
