ALTER TABLE CADDIS_DEV.P_CLASS_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_CLASS_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_CLASS_DETAILS
(
  CLASS_DETAIL_ID      NUMBER(11)               NOT NULL,
  CAUSE_EFFECT_ID      NUMBER(12)               NOT NULL,
  CLASS_DESCRIPTOR_ID  NUMBER(11)               NOT NULL,
  CAUSE_MEAN           NUMBER,
  CAUSE_MIN            NUMBER,
  CAUSE_MAX            NUMBER,
  CAUSE_STANDARD_DEV   NUMBER,
  CREATE_DATE          DATE,
  CREATE_USER          VARCHAR2(50 BYTE),
  UPDATE_DATE          DATE,
  UPDATE_USER          VARCHAR2(50 BYTE),
  APPEND_QUERY         VARCHAR2(250 BYTE),
  EFFECT_MEAN          NUMBER,
  EFFECT_MIN           NUMBER,
  EFFECT_MAX           NUMBER,
  EFFECT_STANDARD_DEV  NUMBER,
  COMMENTS             VARCHAR2(4000 CHAR)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_CLASS_DETAILS_CAU_EFF_ID ON CADDIS_DEV.P_CLASS_DETAILS
(CAUSE_EFFECT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_CLASS_DETAILS_CLA_DES_ID ON CADDIS_DEV.P_CLASS_DETAILS
(CLASS_DESCRIPTOR_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_CLASS_DETAILS ON CADDIS_DEV.P_CLASS_DETAILS
(CLASS_DETAIL_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.UX_P_CLASS_DETAILS_2IDS ON CADDIS_DEV.P_CLASS_DETAILS
(CAUSE_EFFECT_ID, CLASS_DESCRIPTOR_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_CLASS_DETAILS_T1" 
 BEFORE INSERT OR UPDATE ON  "P_CLASS_DETAILS" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_CLASS_DETAILS ADD (
  CONSTRAINT PK_P_CLASS_DETAILS
  PRIMARY KEY
  (CLASS_DETAIL_ID)
  USING INDEX CADDIS_DEV.PK_P_CLASS_DETAILS,
  CONSTRAINT UX_P_CLASS_DETAILS_2IDS
  UNIQUE (CAUSE_EFFECT_ID, CLASS_DESCRIPTOR_ID)
  USING INDEX CADDIS_DEV.UX_P_CLASS_DETAILS_2IDS);

ALTER TABLE CADDIS_DEV.P_CLASS_DETAILS ADD (
  CONSTRAINT FK_P_CLASS_DETAILS_CAU_EFF_ID 
  FOREIGN KEY (CAUSE_EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_CAUSE_EFFECT (CAUSE_EFFECT_ID),
  CONSTRAINT FK_P_CLASS_DETAILS_CLA_DES_ID 
  FOREIGN KEY (CLASS_DESCRIPTOR_ID) 
  REFERENCES CADDIS_DEV.P_CLASS_DESCRIPTOR (CLASS_DESCRIPTOR_ID)
  ON DELETE SET NULL);
  
  DROP SEQUENCE CADDIS_DEV.SEQ_CLASS_DETAIL_ID;

CREATE SEQUENCE CADDIS_DEV.SEQ_CLASS_DETAIL_ID
  START WITH 114028
  MAXVALUE 999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
