ALTER TABLE CADDIS_DEV.P_CLASS_DESCRIPTOR
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_CLASS_DESCRIPTOR CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_CLASS_DESCRIPTOR
(
  CLASS_DESCRIPTOR_ID      NUMBER(11)           NOT NULL,
  CLASS_DESCRIPTOR         VARCHAR2(50 BYTE),
  NUM_CLASSES_DESCRIPTORS  NUMBER(11),
  CREATE_DATE              DATE,
  CREATE_USER              VARCHAR2(50 BYTE),
  UPDATE_DATE              DATE,
  UPDATE_USER              VARCHAR2(50 BYTE),
  APPEND_QUERY             VARCHAR2(250 BYTE),
  DATASET_ID               NUMBER(11)           NOT NULL
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_CLASS_DES_DATASET_ID ON CADDIS_DEV.P_CLASS_DESCRIPTOR
(DATASET_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.IX_P_CLASS_DES_NUM_CLA_DES ON CADDIS_DEV.P_CLASS_DESCRIPTOR
(NUM_CLASSES_DESCRIPTORS)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_CLASS_DESCRIPTOR2 ON CADDIS_DEV.P_CLASS_DESCRIPTOR
(CLASS_DESCRIPTOR_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_CLASS_DESCRIPTOR_T1" 
 BEFORE INSERT OR UPDATE ON  "P_CLASS_DESCRIPTOR" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_CLASS_DESCRIPTOR ADD (
  CONSTRAINT PK_P_CLASS_DESCRIPTOR2
  PRIMARY KEY
  (CLASS_DESCRIPTOR_ID)
  USING INDEX CADDIS_DEV.PK_P_CLASS_DESCRIPTOR2);

ALTER TABLE CADDIS_DEV.P_CLASS_DESCRIPTOR ADD (
  CONSTRAINT FK_P_CLASS_DES_DATASET_ID 
  FOREIGN KEY (DATASET_ID) 
  REFERENCES CADDIS_DEV.P_DATASET (DATASET_ID)
  ON DELETE SET NULL);

DROP SEQUENCE CADDIS_DEV.SEQ_CLASS_DESCRIPTOR_ID;

CREATE SEQUENCE CADDIS_DEV.SEQ_CLASS_DESCRIPTOR_ID
  START WITH 8826
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;