ALTER TABLE CADDIS_DEV.P_EFFECT_MEASURED
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_EFFECT_MEASURED CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_EFFECT_MEASURED
(
  EFFECT_MEASURED_ID          NUMBER(11)        NOT NULL,
  MEASUREMENT_METHOD          VARCHAR2(3000 BYTE),
  EFFECT_COMMENT              VARCHAR2(4000 BYTE),
  CREATE_DATE                 DATE,
  CREATE_USER                 VARCHAR2(50 BYTE),
  UPDATE_DATE                 DATE,
  UPDATE_USER                 VARCHAR2(50 BYTE),
  LL_EFFECT_MEASURED_UNIT_ID  NUMBER(11),
  CAUSE_EFFECT_ID             NUMBER(12)        NOT NULL,
  RESPONSE_DATA_ORIGIN        VARCHAR2(250 CHAR),
  LL_CLASS_ID                 NUMBER(11),
  LL_EFFECT_SET_TEST_TYPE_ID  NUMBER(11)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_EFFECT_MEASURED_CA_EFF_ID ON CADDIS_DEV.P_EFFECT_MEASURED
(CAUSE_EFFECT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_EFF_MS_EFF_MS_UNIT_ID ON CADDIS_DEV.P_EFFECT_MEASURED
(LL_EFFECT_MEASURED_UNIT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_EFFECT_MS_EFFECT_MS_ID ON CADDIS_DEV.P_EFFECT_MEASURED
(EFFECT_MEASURED_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_EFFECT_MEASURED_T1" 
 BEFORE INSERT OR UPDATE ON  "P_EFFECT_MEASURED" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_EFFECT_MEASURED ADD (
  CONSTRAINT PK_P_EFFECT_MS_EFFECT_MS_ID
  PRIMARY KEY
  (EFFECT_MEASURED_ID)
  USING INDEX CADDIS_DEV.PK_P_EFFECT_MS_EFFECT_MS_ID);

ALTER TABLE CADDIS_DEV.P_EFFECT_MEASURED ADD (
  CONSTRAINT FK_P_EFFECT_MEASURED_CA_EFF_ID 
  FOREIGN KEY (CAUSE_EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_CAUSE_EFFECT (CAUSE_EFFECT_ID),
  CONSTRAINT FK_P_EFFECT_MEASURED_CLASS_ID 
  FOREIGN KEY (LL_CLASS_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_EFF_MS_EFF_MS_UNIT_ID 
  FOREIGN KEY (LL_EFFECT_MEASURED_UNIT_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT P_EFF_MEASURED_TEST_TYPE_ID 
  FOREIGN KEY (LL_EFFECT_SET_TEST_TYPE_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);
  
  DROP SEQUENCE CADDIS_DEV.SEQ_EFFECT_MEASURED_ID;

CREATE SEQUENCE CADDIS_DEV.SEQ_EFFECT_MEASURED_ID
  START WITH 24548
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
