ALTER TABLE CADDIS_DEV.P_SI_SIGNIFICANTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CADDIS_DEV.P_SI_SIGNIFICANTS CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.P_SI_SIGNIFICANTS
(
  SI_SIGNIFICANT_ID    NUMBER(11)               NOT NULL,
  SI_IMPORTANCE_COMM   VARCHAR2(4000 BYTE),
  CREATE_DATE          DATE,
  CREATE_USER          VARCHAR2(50 BYTE),
  UPDATE_DATE          DATE,
  UPDATE_USER          VARCHAR2(50 BYTE),
  CAUSE_EFFECT_ID      NUMBER(12)               NOT NULL,
  LL_SI_SIG_ID         NUMBER(11),
  LL_DATASET_CLASS_ID  NUMBER(11),
  LL_SI_EVIDENCE_ID    NUMBER(11)
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CADDIS_DEV.FK_P_SI_SIG_DATASET_CLASS_ID ON CADDIS_DEV.P_SI_SIGNIFICANTS
(LL_DATASET_CLASS_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CADDIS_DEV.FK_P_SI_SIG_LL_SI_SIG_ID ON CADDIS_DEV.P_SI_SIGNIFICANTS
(LL_SI_SIG_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CADDIS_DEV.PK_P_SI_SIGNIFICANTS2 ON CADDIS_DEV.P_SI_SIGNIFICANTS
(SI_SIGNIFICANT_ID)
LOGGING
TABLESPACE CADDIS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER CADDIS_DEV."P_SI_SIGNIFICANTS_T1" 
 BEFORE INSERT OR UPDATE ON  "P_SI_SIGNIFICANTS" 
 REFERENCING OLD AS "OLD" NEW AS "NEW"
 FOR EACH ROW
begin
   begin 
      if inserting then
           :NEW.CREATE_DATE := SYSDATE;
           :NEW.CREATE_USER := nvl(v('APP_USER'),USER);    
      end if;
      if updating then
        :NEW.UPDATE_DATE := SYSDATE;
        :NEW.UPDATE_USER  := nvl(v('APP_USER'),USER);
      end if;
   end;
end;
/


ALTER TABLE CADDIS_DEV.P_SI_SIGNIFICANTS ADD (
  CONSTRAINT PK_P_SI_SIGNIFICANTS2
  PRIMARY KEY
  (SI_SIGNIFICANT_ID)
  USING INDEX CADDIS_DEV.PK_P_SI_SIGNIFICANTS2);

ALTER TABLE CADDIS_DEV.P_SI_SIGNIFICANTS ADD (
  CONSTRAINT FK_P_SI_SIG_CAU_EFF_ID 
  FOREIGN KEY (CAUSE_EFFECT_ID) 
  REFERENCES CADDIS_DEV.P_CAUSE_EFFECT (CAUSE_EFFECT_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_SI_SIG_DATASET_CLASS_ID 
  FOREIGN KEY (LL_DATASET_CLASS_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_P_SI_SIG_LL_SI_SIG_ID 
  FOREIGN KEY (LL_SI_SIG_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL,
  CONSTRAINT FK_SIGNIFICANTS_EVIDENCE_ID 
  FOREIGN KEY (LL_SI_EVIDENCE_ID) 
  REFERENCES CADDIS_DEV.P_LIST_ITEM (LL_ID)
  ON DELETE SET NULL);

DROP SEQUENCE CADDIS_DEV.SEQ_SI_SIGNIFICANT_ID;

CREATE SEQUENCE CADDIS_DEV.SEQ_SI_SIGNIFICANT_ID
  START WITH 23810
  MAXVALUE 999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
