SELECT a.SHAPE_LINKAGE_ID
	,b.SHAPE_ID AS FR_SHAPE_ID
	,b.SHAPE_LABEL AS FR_SHAPE_LABEL
	,b.STANDARD_TERM_ID AS FR_STANDARD_TERM_ID
	,b.LL_SHAPE_LABEL_SYMBOL_ID AS FR_SHAPE_SYMBOL_ID
	,DECODE(b.LL_SHAPE_LABEL_SYMBOL_ID, 20026, 30418, 20027, 30419, 20028, 30420, 30421) AS FR_TRAJECTORY_ID
	,c.SHAPE_ID AS TO_SHAPE_ID
	,c.SHAPE_LABEL AS TO_SHAPE_LABEL
	,c.STANDARD_TERM_ID AS TO_STANDARD_TERM_ID
	,c.LL_SHAPE_LABEL_SYMBOL_ID AS TO_SHAPE_SYMBOL_ID
	,DECODE(c.LL_SHAPE_LABEL_SYMBOL_ID, 20026, 30418, 20027, 30419, 20028, 30420, 30421) AS TO_TRAJECTORY_ID
	,d.CITATION_ID
FROM ICD_SHAPE_LINKAGE a
	,ICD_SHAPE b
	,ICD_SHAPE c
	,ICD_LINKAGE_CITATION_JOIN d
WHERE a.SHAPE_FROM_ID = b.SHAPE_ID
	AND a.SHAPE_TO_ID = c.SHAPE_ID
	AND a.SHAPE_LINKAGE_ID = d.SHAPE_LINKAGE_ID;

SELECT DISTINCT a.SHAPE_LINKAGE_ID
	,b.SHAPE_ID AS FR_SHAPE_ID
	,b.SHAPE_LABEL AS FR_SHAPE_LABEL
	--,e.STANDARD_TERM_ID AS FR_STANDARD_TERM_ID
	--,b.STANDARD_TERM_ID AS FR_STANDARD_TERM_ID
	,b.LL_SHAPE_LABEL_SYMBOL_ID AS FR_SHAPE_SYMBOL_ID
	,DECODE(b.LL_SHAPE_LABEL_SYMBOL_ID, 20026, 30418, 20027, 30419, 20028, 30420, 30421) AS FR_TRAJECTORY_ID
	,c.SHAPE_ID AS TO_SHAPE_ID
	,c.SHAPE_LABEL AS TO_SHAPE_LABEL
	--,f.STANDARD_TERM_ID AS TO_STANDARD_TERM_ID
	--,c.STANDARD_TERM_ID AS TO_STANDARD_TERM_ID
	,c.LL_SHAPE_LABEL_SYMBOL_ID AS TO_SHAPE_SYMBOL_ID
	,DECODE(c.LL_SHAPE_LABEL_SYMBOL_ID, 20026, 30418, 20027, 30419, 20028, 30420, 30421) AS TO_TRAJECTORY_ID
	,d.CITATION_ID
FROM ICD_SHAPE_LINKAGE a
	,ICD_SHAPE b
	,ICD_SHAPE c
	,ICD_LINKAGE_CITATION_JOIN d
	--,P_STANDARD_TERM e
	--,P_STANDARD_TERM f
WHERE a.SHAPE_FROM_ID = b.SHAPE_ID
	AND a.SHAPE_TO_ID = c.SHAPE_ID
	AND a.SHAPE_LINKAGE_ID = d.SHAPE_LINKAGE_ID
	--AND lower(b.SHAPE_LABEL) = lower(e.STANDARD_TERM)
	--AND lower(c.SHAPE_LABEL) = lower(f.STANDARD_TERM)
	ORDER BY 1

