DROP VIEW CADDIS_DEV.V_ICD_DIAGRAM_SHAPE;

/* Formatted on 3/14/2016 1:42:50 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW CADDIS_DEV.V_ICD_DIAGRAM_SHAPE
(
   DIAGRAM_ID,
   SHAPE_ID,
   SHAPE_COLOR,
   SHAPE_LABEL,
   SHAPE_WIDTH,
   SHAPE_HEIGHT,
   SHAPE_THICKNESS,
   PARENT_SHAPE_ID,
   SHAPE_TYPE,
   LL_LEGEND_FILTER_ID,
   LL_SHAPE_LABEL_SYMBOL_ID,
   STANDARD_TERM_ID,
   TOP_LEFT_CORNER_PT_X,
   TOP_LEFT_CORNER_PT_Y,
   SHAPE_BIN_INDEX
)
AS
   SELECT dsj.DIAGRAM_ID AS DIAGRAM_ID,
          s.SHAPE_ID AS SHAPE_ID,
          s.SHAPE_COLOR AS SHAPE_COLOR,
          s.SHAPE_LABEL AS SHAPE_LABEL,
          s.SHAPE_WIDTH AS SHAPE_WIDTH,
          s.SHAPE_HEIGHT AS SHAPE_HEIGHT,
          s.SHAPE_THICKNESS AS SHAPE_THICKNESS,
          s.PARENT_SHAPE_ID AS PARENT_SHAPE_ID,
          s.SHAPE_TYPE AS SHAPE_TYPE,
          s.LL_LEGEND_FILTER_ID AS LL_LEGEND_FILTER_ID,
          s.LL_SHAPE_LABEL_SYMBOL_ID AS LL_SHAPE_LABEL_SYMBOL_ID,
          s.STANDARD_TERM_ID AS STANDARD_TERM_ID,
          s.TOP_LEFT_CORNER_PT_X AS TOP_LEFT_CORNER_PT_X,
          s.TOP_LEFT_CORNER_PT_Y AS TOP_LEFT_CORNER_PT_Y,
          s.SHAPE_BIN_INDEX AS SHAPE_BIN_INDEX
     FROM ICD_SHAPE s, ICD_DIAGRAM_SHAPE_JOIN dsj
    WHERE dsj.SHAPE_ID = s.SHAPE_ID;
