CREATE OR REPLACE FORCE VIEW CADDIS_DEV.V_STUDY_TYPE
(
   LL_ID,
   LIST_ITEM_CODE,
   LIST_ITEM_DESCRIPTION,
   IS_PENDING,
   IS_ARCHIVED,
   ORDER_NUMBER,
   REVIEWER,
   ENTERED_BY,
   DATETIME,
   LIST_ITEM_DESCRIPTION_LONG,
   LL_PARA_CLASS_ID,
   LL_PARA_GROUP_ID,
   LL_ID_PARENT
)
AS
   SELECT LL_ID,
          LIST_ITEM_CODE,
          LIST_ITEM_DESCRIPTION,
          IS_PENDING,
          IS_ARCHIVED,
          ORDER_NUMBER,
          REVIEWER,
          ENTERED_BY,
          DATETIME,
          LIST_ITEM_DESCRIPTION_LONG,
          LL_PARA_CLASS_ID,
          LL_PARA_GROUP_ID,
          LL_ID_PARENT
     FROM P_LIST_ITEM
    WHERE TYPE_ENTITY_ID = (SELECT TYPE_ENTITY_ID
                              FROM P_TYPE_ENTITY_NAME
                             WHERE TYPE_ENTITY_NAME = 'STUDY TYPE');