
package org.eel.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EELServices", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://staging.toolkit.net.au/Tools/Online/EE/EELServices.svc?wsdl")
public class EELServices
    extends Service
{

    private final static URL EELSERVICES_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://www.toolkit.net.au/Tools/Online/EE/EELServices.svc?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        EELSERVICES_WSDL_LOCATION = url;
    }

    public EELServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EELServices() {
        super(EELSERVICES_WSDL_LOCATION, new QName("http://tempuri.org/", "EELServices"));
    }

    /**
     * 
     * @return
     *     returns IEELServices
     */
    @WebEndpoint(name = "BasicHttpBinding_IEELServices")
    public IEELServices getBasicHttpBindingIEELServices() {
        return (IEELServices)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEELServices"), IEELServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEELServices
     */
    @WebEndpoint(name = "BasicHttpBinding_IEELServices")
    public IEELServices getBasicHttpBindingIEELServices(WebServiceFeature... features) {
        return (IEELServices)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEELServices"), IEELServices.class, features);
    }

}
