--DROP TABLE CADDIS_DEV.CONFIG CASCADE CONSTRAINTS;

CREATE TABLE CADDIS_DEV.CONFIG
(
  PARAMETER_NAME         VARCHAR2(300 CHAR)     NOT NULL,
  PARAMETER_VALUE        VARCHAR2(300 CHAR)     NOT NULL,
  PARAMETER_DESCRIPTION  VARCHAR2(4000 CHAR)    NOT NULL
)
TABLESPACE CADDIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP SYNONYM  CADDIS2_APEX.CONFIG;

CREATE SYNONYM CADDIS2_APEX.CONFIG FOR CADDIS_DEV.CONFIG;


GRANT SELECT ON CADDIS_DEV.CONFIG TO CADDIS2_APEX;

INSERT INTO CADDIS_DEV.CONFIG VALUES('WS_AUTH', 'https://ssoprod.epa.gov/iamfw/', 'Use WAM service ');

